# -*- coding: utf-8 -*-
"""HW1Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RRE0zB0bIBlPVlUQHR1v1-EKFjTir-Te
"""

from keras.datasets import mnist
import numpy as np
import matplotlib.pyplot as plt
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

#array creation
avg_images = np.zeros((10,28,28))
image_counts = np.zeros(10,)

for i in range (len(train_images)):
  index = train_labels[i] - 1
  avg_images[index] += train_images[i]
  image_counts[index] += 1
  
for i in range (len(avg_images)):
  avg_images[i] /= image_counts[i]
  
  
plt.figure(figsize=(10, 10))
plt.suptitle("Average Numbers")
for i in range(len(avg_images)):
  plt.subplot(10, 10, i + 1)
  plt.xticks([])
  plt.yticks([])
  plt.imshow(avg_images[i])
plt.show()

