# -*- coding: utf-8 -*-
"""HW1Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OfVrkGZpeWa9Oyp7GcSHsAAcrV5cTaLu
"""

# Commented out IPython magic to ensure Python compatibility.
from mpl_toolkits import mplot3d
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
def f(x, y):
    return -(x**2) - (y**2)
 
x = np.linspace(-100,100)
y = np.linspace(-100,100)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)


fig = plt.figure()
ax = plt.axes(projection='3d')
ax.plot([0], [0], [0], marker='.', markersize=15, alpha=1, zorder=100)
ax.text(15, 0.5, 1500,'Local Maxima (0,0,0)', zorder=100)
ax.contour3D(X, Y, Z, 50, cmap='binary')

ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z');

# Commented out IPython magic to ensure Python compatibility.
from mpl_toolkits import mplot3d
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
def f(x, y):
    return (x**2) + (y**2)
 
x = np.linspace(-100,100)
y = np.linspace(-100,100)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)



fig = plt.figure()
ax = plt.axes(projection='3d')

ax.contour3D(X, Y, Z, 50, cmap='binary')
ax.plot([0], [0], [0], marker='.', markersize=15, alpha=1, zorder=100)
ax.text(15, 0.5, 1.9,'Local Minima (0,0,0)', zorder=100)

ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z');

# Commented out IPython magic to ensure Python compatibility.
from mpl_toolkits import mplot3d
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
def f(x, y):
    return (x**2) - (y**2)
 
x = np.linspace(-50,50)
y = np.linspace(-50,50)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)


fig = plt.figure()
ax = plt.axes(projection='3d')

ax.contour3D(X, Y, Z, 50, cmap='binary')
ax.plot([0], [0], [0], marker='.', markersize=15, alpha=1, zorder=100)
ax.text(-30, 0.5, 2500,'Saddle Point Gradient=0 (0,0,0)', zorder=100)

ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z');